<%@ Page Language="C#" MasterPageFile="~/User/user.Master" AutoEventWireup="true" CodeBehind="Bids.aspx.cs" Inherits="AuctionOnline.User.WebForm5" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<title>Bids Section</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <asp:Label ID="Label1" runat="server" ForeColor="White"></asp:Label>
    <asp:LinkButton ID="LinkButton1"
        runat="server" onclick="LinkButton1_Click">Log Out</asp:LinkButton>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
   <ContentTemplate>
   <p>
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" 
            onselectedindexchanged="DropDownList1_SelectedIndexChanged">
            <asp:ListItem Value="0">Stock</asp:ListItem>
            <asp:ListItem Value="1">Not In Stock</asp:ListItem>
        </asp:DropDownList>
        <br />
    </p>
    <p>
        <asp:MultiView ID="MultiView1" runat="server">
            <asp:View ID="View1" runat="server">
            <asp:Label ID="Label2" runat="server" ForeColor="Red"></asp:Label>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateEditButton="True" onrowediting="GridView1_RowEditing" 
                    onrowcancelingedit="GridView1_RowCancelingEdit" 
                    onrowupdating="GridView1_RowUpdating" Width="695px" DataKeyNames="bid_id" 
                    AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" 
                    GridLines="None" onrowdeleting="GridView1_RowDeleting" >
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
               <Columns>
            <asp:BoundField DataField="bid_id" HeaderText="bid_id" />
            <asp:BoundField DataField="bDate" HeaderText="bDate" />
            <asp:BoundField DataField="p_name" HeaderText="p_name" />
            <asp:BoundField DataField="Bprice" HeaderText="Bprice" />
               </Columns>            
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#999999" />
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                </asp:GridView> 
            
            
            </asp:View>
            <asp:View ID="View2" runat="server">
            <asp:Label ID="Label3" runat="server" ForeColor="Red"></asp:Label>
                <asp:GridView ID="GridView2" runat="server" CellPadding="4" ForeColor="#333333" 
                    GridLines="None" Width="693px" AutoGenerateColumns="False" 
                    DataKeyNames="bid_id" onrowcancelingedit="GridView2_RowCancelingEdit" 
                    onrowdeleting="GridView2_RowDeleting" onrowediting="GridView2_RowEditing" 
                    onrowupdating="GridView2_RowUpdating" AutoGenerateDeleteButton="True" >
               <Columns>
            <asp:BoundField DataField="bid_id" HeaderText="bid_id" />
            <asp:BoundField DataField="bDate" HeaderText="bDate" />
            <asp:BoundField DataField="p_name" HeaderText="p_name" />
            <asp:BoundField DataField="Bprice" HeaderText="Bprice" />
               </Columns>            
                  
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#999999" />
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
               
       
      
               
                </asp:GridView>
           
            </asp:View>
            <br />
        </asp:MultiView>
    </p>
   
   
   
   </ContentTemplate>
   
    </asp:UpdatePanel>
    
    
</asp:Content>
